[package]
name = "frontend"
version = "0.1.0"
edition = "2018"

[dependencies]
yew = "0.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
chrono = "0.4"

js-sys = "0.3.52"